---
- name: Update apt cache
  apt:
    update_cache: yes
    cache_valid_time: 3600
  become: yes

- name: Install required packages
  apt: name={{ item }} state=present
  with_items:
    - pwgen
    - sshpass
  become: yes
